// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3n19jeMJ13n1aNQYCMfYEATyWui30Ly4',
    appId: '1:935193837773:web:0928649f71ff437509a984',
    messagingSenderId: '935193837773',
    projectId: 'fir-fluttercodelab-9b7b8',
    authDomain: 'fir-fluttercodelab-9b7b8.firebaseapp.com',
    storageBucket: 'fir-fluttercodelab-9b7b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgoMshZHlEqsbZ_VO_z9V0pSw0JUR__LQ',
    appId: '1:935193837773:android:b47c2c26b31729dd09a984',
    messagingSenderId: '935193837773',
    projectId: 'fir-fluttercodelab-9b7b8',
    storageBucket: 'fir-fluttercodelab-9b7b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtsZ4ID1QoTe_EFEGTsROeAI6q4t4uIOg',
    appId: '1:935193837773:ios:718e3d004e27d6c209a984',
    messagingSenderId: '935193837773',
    projectId: 'fir-fluttercodelab-9b7b8',
    storageBucket: 'fir-fluttercodelab-9b7b8.appspot.com',
    iosBundleId: 'com.example.firebasefluttercodelab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtsZ4ID1QoTe_EFEGTsROeAI6q4t4uIOg',
    appId: '1:935193837773:ios:718e3d004e27d6c209a984',
    messagingSenderId: '935193837773',
    projectId: 'fir-fluttercodelab-9b7b8',
    storageBucket: 'fir-fluttercodelab-9b7b8.appspot.com',
    iosBundleId: 'com.example.firebasefluttercodelab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3n19jeMJ13n1aNQYCMfYEATyWui30Ly4',
    appId: '1:935193837773:web:a275500900f6e74209a984',
    messagingSenderId: '935193837773',
    projectId: 'fir-fluttercodelab-9b7b8',
    authDomain: 'fir-fluttercodelab-9b7b8.firebaseapp.com',
    storageBucket: 'fir-fluttercodelab-9b7b8.appspot.com',
  );
}